architectures = architectures = {
    'simulation1':{
      'layers':{
          'layer_1':{
              'type':'conv2',
              'parameters':{'filters':64,'kernel_size':9,'padding':'same','activation':'relu','input_shape': (98,98,1)}
          },
          'layer_2':{
              'type':'AveragePooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_3':{
              'type':'conv2',
              'parameters':{'filters':48,'kernel_size':5,'padding':'same','activation':'relu'}
          },
          'layer_4':{
              'type':'maxPooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_5':{
              'type':'conv2',
              'parameters':{'filters':32,'kernel_size':3,'padding':'same','activation':'relu'}
          },
          'layer_6':{
              'type':'AveragePooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_7':{
              'type':'flatten',
              'parameters':None
          },
          'layer_8':{
              'type':'dense',
              'parameters':{'units':500,'activation':'relu'}
          },
          'layer_9':{
              'type':'dense',
              'parameters':{'units':350,'activation':'relu'}
          },
          'layer_10':{
              'type':'dense',
              'parameters':{'units':150,'activation':'relu'}
          },
          'layer_11':{
              'type':'dense',
              'parameters':{'units':2,'activation':'softmax'}
          }
       },
      'compile':{'loss':'sparse_categorical_crossentropy','metrics':['accuracy']},
      'fit':{'epochs':150,'initial_epoch':0,'validation_split':0.2}
    },
    'simulation2':{
      'layers':{
          
        'layer_1':{
              'type':'conv2',
              'parameters':{'filters':96,'kernel_size':13,'padding':'same','activation':'relu','input_shape': (98,98,1)}
          },
          'layer_2':{
              'type':'maxPooling',
              'parameters':{'pool_size':[4,4],'strides':2}
          },

          'layer_3':{
              'type':'conv2',
              'parameters':{'filters':64,'kernel_size':9,'padding':'same','activation':'relu','input_shape': (98,98,1)}
          },
          'layer_4':{
              'type':'AveragePooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_5':{
              'type':'conv2',
              'parameters':{'filters':32,'kernel_size':5,'padding':'same','activation':'relu'}
          },
          'layer_6':{
              'type':'maxPooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_7':{
              'type':'conv2',
              'parameters':{'filters':16,'kernel_size':3,'padding':'same','activation':'relu'}
          },
          'layer_8':{
              'type':'AveragePooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_9':{
              'type':'flatten',
              'parameters':None
          },
          'layer_10':{
              'type':'dense',
              'parameters':{'units':750,'activation':'relu'}
          },
          'layer_11':{
              'type':'dense',
              'parameters':{'units':500,'activation':'relu'}
          },
          'layer_12':{
              'type':'dense',
              'parameters':{'units':250,'activation':'relu'}
          },
          'layer_13':{
              'type':'dense',
              'parameters':{'units':150,'activation':'relu'}
          },
          'layer_14':{
              'type':'dense',
              'parameters':{'units':2,'activation':'softmax'}
          }
       },
      'compile':{'loss':'sparse_categorical_crossentropy','metrics':['accuracy']},
      'fit':{'epochs':150,'initial_epoch':0,'validation_split':0.2}
    },
    'simulation3':{
      'layers':{
          
        'layer_1':{
              'type':'conv2',
              'parameters':{'filters':16,'kernel_size':3,'padding':'same','activation':'relu','input_shape': (98,98,1)}
          },
          'layer_2':{
              'type':'maxPooling',
              'parameters':{'pool_size':[4,4],'strides':2}
          },

          'layer_3':{
              'type':'conv2',
              'parameters':{'filters':32,'kernel_size':5,'padding':'same','activation':'relu','input_shape': (98,98,1)}
          },
          'layer_4':{
              'type':'AveragePooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_5':{
              'type':'conv2',
              'parameters':{'filters':64,'kernel_size':9,'padding':'same','activation':'relu'}
          },
          'layer_6':{
              'type':'maxPooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_7':{
              'type':'conv2',
              'parameters':{'filters':96,'kernel_size':13,'padding':'same','activation':'relu'}
          },
          'layer_8':{
              'type':'AveragePooling',
              'parameters':{'pool_size':[2,2],'strides':2}
          },
          'layer_9':{
              'type':'flatten',
              'parameters':None
          },
          'layer_10':{
              'type':'dense',
              'parameters':{'units':750,'activation':'relu'}
          },
          'layer_11':{
              'type':'dense',
              'parameters':{'units':500,'activation':'relu'}
          },
          'layer_12':{
              'type':'dense',
              'parameters':{'units':250,'activation':'relu'}
          },
          'layer_13':{
              'type':'dense',
              'parameters':{'units':150,'activation':'relu'}
          },
          'layer_14':{
              'type':'dense',
              'parameters':{'units':2,'activation':'softmax'}
          }
       },
      'compile':{'loss':'sparse_categorical_crossentropy','metrics':['accuracy']},
      'fit':{'epochs':150,'initial_epoch':0,'validation_split':0.2}
    }
}
